<?php

namespace App\Http\Controllers;

use App\Models\AllApps;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;


class GitController extends Controller
{

    public function googleAppRes($packageName)
    {

        $gPlay = new \Nelexa\GPlay\GPlayApps();
        $newApp = $gPlay->getNewApps();
        return $newApp;
    }

    public function sendTelegramMessage()
    {

        $removedDate = Carbon::now()->format('d-m-Y');
        $developer = 'Smashing Downloader';
        $package = 'com.savestatusimages.downloadhdvideos.playerhd';
        $appName = 'HD Video Saver Download Videos';
        $appstorespylink = 'https://appstorespy.com/apps/play/HDVideoSaverDownloadVideos/' . $package;

        $telegramMessage = " <u><b>App Name</b></u> : " . $appName . " \n <u><b>Package Name</b></u> : " . $package . " \n <u><b>Developer Name</b></u> : " . $developer . " \n <u><b>Removed Date</b></u> : " . $removedDate . " \n <u><b>AppStoreSpy Link</b></u> : " . $appstorespylink;


        $app_details_link = "https://api.telegram.org/bot6025847479:AAFEsqZ0sNZxD12hzUx-beI88J13U58NuYs/sendMessage?chat_id=5378656582&parse_mode=HTML&text=" . $telegramMessage;
        $res = Http::get($app_details_link);
        if ($res->status() == 200) {

        } else {

        }
    }


    public function getRemovedPackage(){

        $app = AllApps::where('status','removed')->pluck('app_packageName');
    }

}


//Google\AdsApi\AdManager\v202302\CreativePage {#386
//    #totalResultSetSize: 1
//    #startIndex: 0
//    #results: array:1 [
//    0 => Google\AdsApi\AdManager\v202302\AdExchangeCreative {#367
//        #isNativeEligible: false
//        #isInterstitial: false
//        #isAllowsAllRequestedSizes: false
//        #codeSnippet: """
//        // For better performance, we recommend not making any changes to this Ad Exchange
//        // code snippet.
//        // Instead, we recommend that you target your inventory using Inventory rules based
//        // on DFP ad units, placements, and key-values.
//        // As a result, there is no need to copy/paste code from Ad Exchange, but you can
//        // still use certain parameters such as 'google_ad_slot' and 'google_adtest'.
//        """
//      #advertiserId: 5302976842
//      #id: 138430933035
//      #name: "test Multisize - Autogenerated on 27/04/2023, 16:49:42"
//      #size: Google\AdsApi\AdManager\v202302\Size {#384
//        #width: 300
//        #height: 50
//        #isAspectRatio: false
//      }
//      #previewUrl: "https://partner.googleadservices.com/gampad/ads?gct=b9X9TnssP7sK_gGKGPoBKu0BCAkQKEoAuAGr0IHZgwTSAgl0ZXh0L2h0bWzaArsBPHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiPjwhLS0KZ29vZ2xlX3BhZ2VfdXJsPSJodHRwOi8vd3d3Lmdvb2dsZS5jb20iOy8vLS0-PC9zY3JpcHQ-PHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiIHNyYz0iLy9wYWdlYWQyLmdvb2dsZXN5bmRpY2F0aW9uLmNvbS9wYWdlYWQvc2hvd19hZHMuanMiPjwvc2NyaXB0PvACrAL4AjKQAwDIA6wC0AMy8AMCsgECGAHKAQJAARiatqmiBigAMJrS3qkGOABYAWoGX2JsYW5rcM60qaIG&iu=22869856784&gdfp_req=1&height=50&width=300&impl=ifr&sfv=1-0-40"
//      #policyLabels: null
//      #appliedLabels: null
//      #lastModifiedDateTime: Google\AdsApi\AdManager\v202302\DateTime {#382
//        #date: Google\AdsApi\AdManager\v202302\Date {#375
//          #year: 2023
//          #month: 4
//          #day: 27
//        }
//        #hour: 4
//        #minute: 19
//        #second: 42
//        #timeZoneId: "PST8PDT"
//      }
//      #customFieldValues: null
//      #thirdPartyDataDeclaration: null
//    }
//  ]
//}



